### ISSUE TITLE
local modfuncs = require(game.ServerScriptService.GameAdministration.Functions)

### ISSUE THREAD

**Issue by Jhxinie** [littleBitsman/Discord-To-Roblox-Bot#2]
Whenever adding into the game it gives me this within the console as well as a internal error when attempting to execute the command.

**Comment by Jhxinie** [comment]
Also giving me the error of 
`TypeError: Cannot read properties of undefined (reading 'execute')
    at Client.<anonymous> (C:\Users\18157\Desktop\bot\index.js:36:46)
    at Client.emit (node:events:513:28)
    at InteractionCreateAction.handle (C:\Users\18157\Desktop\bot\node_modules\discord.js\src\client\actions\InteractionCreate.js:81:12)
    at Object.module.exports [as INTERACTION_CREATE] (C:\Users\18157\Desktop\bot\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (C:\Users\18157\Desktop\bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (C:\Users\18157\Desktop\bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:481:22)
    at WebSocketShard.onMessage (C:\Users\18157\Desktop\bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:321:10)
    at WebSocket.onMessage (C:\Users\18157\Desktop\bot\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (C:\Users\18157\Desktop\bot\node_modules\ws\lib\websocket.js:1178:20)`

**Comment by littleBitsman** [comment]
The TypeError where `execute` is undefined means that the commands were not found under the directory `./commands` in the folder containing `index.js`.

**Comment by littleBitsman** [comment]
Works fine for me with a fresh install of the repo. Try copying the `config.json` to a new cloned repo.

**Comment by littleBitsman** [comment]
Has this issue been resolved?
